### ISSUE TITLE
Note which edition of the text this is, and provide the other edition

### ISSUE THREAD

**Issue by salty-horse** [standardebooks/mary-shelley_frankenstein#7]
There are [three editions](https://en.wikisource.org/wiki/Frankenstein,_or_the_Modern_Prometheus) of this novel, two available online.
This is the 1831 edition, which includes the introduction.

Please note it on the website, and in the ebook itself.

Also, consider making available an ebook of the 1818 edition. It is different enough, and notable enough, to be available alongside the other edition. [Penguin Classics](https://www.penguinrandomhouse.com/books/557081/frankenstein-the-1818-text-by-mary-shelley-introduction-by-charlotte-gordon-editorial-apparatus-by-charles-e-robinson/) calls it "the 1818 text". Others use the cruder "original uncensored edition" (please don't).

**Comment by acabal** [comment]
I can add a note about the edition, but we won't be hosting any other editions. See https://standardebooks.org/contribute/collections-policy
